keys:
  - &admin_insomniac age1yygcmzu8ahvd2uuqsdez2k5jj99f9uuupudzj625lus5cr8nfsqspndkvq
  - &server_John age1ry8hfkhrnznhc8lhdls0ag55x2asrs6j4jhktmzz6vkpelh05geqqczv37
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini|ovpn|txt|crt|nmconnection|8021x)$
    key_groups:
      - age:
          - *admin_insomniac
          - *server_John
