{...}: ''
  www.accuweather.com awxcdn.com * noop
  www.accuweather.com a1060.dscapi5.akamai.net * noop
  www.accuweather.com dscx.akamaiedge.net * noop
  www.accuweather.com mapbox.com * noop
  www.accuweather.com videoplayerhub.com * noop
  www.amazon.es a2z.com * noop
  www.amazon.es amazon.co.uk * noop
  www.amazon.es amazon.com * noop
  www.amazon.es amazon.map.fastly.net * noop
  www.amazon.es media-amazon.com * noop
  www.amazon.es ssl-images-amazon.com * noop
  behind-the-scene * * noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p noop
  behind-the-scene * 3p-frame noop
  behind-the-scene * 3p-script noop
  behind-the-scene * image noop
  behind-the-scene * inline-script noop
  account.clio.com google.com * noop
  account.clio.com gstatic.com * noop
  app.clio.com d2jai5xo6vhevf.cloudfront.net * noop
  discord.com discord.gg * noop
  discord.com discordapp.com * noop
  discord.com hcaptcha.com * noop
  www.dropbox.com 127.0.0.1 * noop
  www.dropbox.com i-phx02p-cor006.api.p001.1drv.com * noop
  www.dropbox.com arkoselabs.com * noop
  www.dropbox.com b-msedge.net * noop
  www.dropbox.com b-0016.b-msedge.net * noop
  www.dropbox.com com.cdn.cloudflare.net * noop
  www.dropbox.com cfl.dropboxstatic.com.cdn.cloudflare.net * noop
  www.dropbox.com dropbox-dns.com * noop
  www.dropbox.com dropboxcaptcha.com * noop
  www.dropbox.com dropboxexperiment.com * noop
  www.dropbox.com dropboxstatic.com * noop
  www.dropbox.com cfl.dropboxstatic.com * noop
  www.dropbox.com fjord.dropboxstatic.com * noop
  www.dropbox.com dropboxusercontent.com * noop
  www.dropbox.com dscd.akamaiedge.net * noop
  www.dropbox.com live.com * noop
  www.dropbox.com office.net * noop
  www.dropbox.com wac-dc-msedge.net * noop
  www.dropbox.com wac-msedge.net * noop
  element.io cloudflare.com * noop
  element.io d3e54v103j8qbb.cloudfront.net * noop
  app.element.io matrix.org * noop
  app.element.io vector.im * noop
  www.figma.com d3otp6i141k5zo.cloudfront.net * noop
  www.figma.com statsigapi.net * noop
  www.geoguessr.com api-prod-4496424.eu-west-1.elb.amazonaws.com * noop
  www.geoguessr.com google.com * noop
  www.geoguessr.com gstatic.com * noop
  www.geoguessr.com maps.googleapis.com * noop
  www.geoguessr.com streetviewpixels-pa.googleapis.com * noop
  github.com avatars.githubusercontent.com * noop
  github.com githubassets.com * noop
  google.com googleusercontent.com * noop
  google.com gstatic.com * noop
  www.google.com measurementlab.net * noop
  monkey-type.firebaseapp.com www.googleapis.com * noop
  monkeytype.com google.com * noop
  monkeytype.com gstatic.com * noop
  monkeytype.com identitytoolkit.googleapis.com * noop
  monkeytype.com monkey-type.firebaseapp.com * noop
  monkeytype.com www.googleapis.com * noop
  www.reddit.com reddit.map.fastly.net * noop
  www.reddit.com redditstatic.com * noop
  robinhood.com d2ue93q3u507c2.cloudfront.net * noop
  www.speedtest.net cdnst.net * noop
  www.speedtest.net ooklaserver.net * noop
  www.speedtest.net speedtest.toob.co.uk * noop
  www.speedtest.net zd.map.fastly.net * noop
  www.youtube.com ggpht.com * noop
  www.youtube.com google.com * noop
  www.youtube.com googleusercontent.com * noop
  www.youtube.com googlevideo.com * noop
  www.youtube.com gstatic.com * noop
  www.youtube.com jnn-pa.googleapis.com * noop
  www.youtube.com ytimg.com * noop
  www.youtube.com i.ytimg.com * noop
''
